### ISSUE TITLE
coredump when freeing riak_get_response that has siblings

### ISSUE THREAD

**Issue by jrwest** [basho-labs/riak-c-client#16]
Sorry to just leave this here and run. This is as far as I got before I had to move on for a bit and just wanted to put the information I had somewhere. 

```
$ ./examples/build/riakc_example --get --bucket v --key f                                           riak-c-arch/riak-c-client | develop
option -b with value `v'
option -k with value `f'
V-Clock: 6bce61606060cc60ca05521c478336720795479766302532e5b132ec6a7d739a2f0b00
Unmodified: false
Deleted: false
Objects: 2
Bucket:
Value: 345
Last Mod: 2013-11-04 12:55:22
Last Mod uSecs: 121770
VTag: 6OCDuWUG8b3e9ssRLzMGP1

*** Error in `./examples/build/riakc_example': double free or corruption (out): 0x0000000000416240 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x72ecf)[0x7fa57cf8cecf]
/usr/lib/libc.so.6(+0x7869e)[0x7fa57cf9269e]
/usr/lib/libc.so.6(+0x79377)[0x7fa57cf93377]
./examples/build/riakc_example[0x403de9]
./examples/build/riakc_example[0x409bfe]
./examples/build/riakc_example[0x40901b]
./examples/build/riakc_example[0x405a7f]
./examples/build/riakc_example[0x401c91]
/usr/lib/libc.so.6(__libc_start_main+0xf5)[0x7fa57cf3bbc5]
./examples/build/riakc_example[0x4017a9]
======= Memory map: ========
...
7fa57e280000-7fa57e282000 rw-p 00000000 00:00 0 zsh: abort (core dumped)  ./examples/build/riakc_example --get --bucket v --key f
```

A quick `gdb` session seems to indicate we are passing a `riak_object *` instead of a `riak_object **` as the second argument to `riak_object_free` inside `riak_object_free_array` but I haven't yet figured out how:

```
(gdb) b riak_print_get_response
Breakpoint 1 at 0x405886: file build/riak_messages.c, line 336.
(gdb) b riak_object_free
Breakpoint 2 at 0x409bdc: file build/riak_object.c, line 583.
(gdb) run --get --bucket v --key f
Starting program: /home/jordan/sandbox/basho/ongoing/riak-c-arch/riak-c-client/examples/build/riakc_example --get --bucket v --key f
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7ffff7ffa000
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
option -b with value `v'
option -k with value `f'

Breakpoint 1, riak_print_get_response (response=0x629280, target=0x7fffffffad40 "", len=10240) at build/riak_messages.c:336
336         riak_int32_t left_to_write = len;
(gdb) print response->content[0]
$1 = (riak_object *) 0x626730
(gdb) print response->content[1]
$2 = (riak_object *) 0x626830
(gdb) c
Continuing.
V-Clock: 6bce61606060cc60ca05521c478336720795479766302532e5b132ec6a7d739a2f0b00
Unmodified: false
Deleted: false
Objects: 2
Bucket:
Value: 345
Last Mod: 2013-11-04 12:55:22
Last Mod uSecs: 121770
VTag: 6OCDuWUG8b3e9ssRLzMGP1

Breakpoint 2, riak_object_free (ctx=0x6255f0, obj=0x6265b0) at build/riak_object.c:583
583       riak_object* object = *obj;
(gdb) print *obj
$5 = (riak_object *) 0x626730
(gdb) bt
#0  riak_object_free (ctx=0x6255f0, obj=0x6265b0) at build/riak_object.c:583
#1  0x000000000040901b in riak_object_free_array (ctx=0x6255f0, array=0x6292a0, len=2) at build/riak_object.c:335
#2  0x0000000000405a7f in riak_free_get_response (ctx=0x6255f0, resp=0x7fffffffad18) at build/riak_messages.c:371
#3  0x0000000000401c91 in main (argc=6, argv=0x7fffffffe7b8) at examples/build/example.c:124
(gdb) c
Continuing.

Breakpoint 2, riak_object_free (ctx=0x6255f0, obj=0x622830) at build/riak_object.c:583
583       riak_object* object = *obj;
(gdb) print *obj
$7 = (riak_object *) 0x416260 <rpb_get_resp__descriptor>
(gdb) bt
#0  riak_object_free (ctx=0x6255f0, obj=0x622830) at build/riak_object.c:583
#1  0x000000000040901b in riak_object_free_array (ctx=0x6255f0, array=0x6292a0, len=2) at build/riak_object.c:335
#2  0x0000000000405a7f in riak_free_get_response (ctx=0x6255f0, resp=0x7fffffffad18) at build/riak_messages.c:371
#3  0x0000000000401c91 in main (argc=6, argv=0x7fffffffe7b8) at examples/build/example.c:124
(gdb) c
Continuing.
*** Error in `/home/jordan/sandbox/basho/ongoing/riak-c-arch/riak-c-client/examples/build/riakc_example': double free or corruption (out
```

**Comment by hazen** [comment]
@jrwest Does this happen on any GET? Which OS?

**Comment by jrwest** [comment]
@javajolt any GET where the returned value has siblings. 

ArchLinux:

```
Linux ... 3.11.6-1-ARCH #1 SMP PREEMPT ... x86_64 GNU/Linux
```

**Comment by hazen** [comment]
Closing this since it is addressed by https://github.com/basho/riak-c-client/pull/23
